"""apf-76s: privacy-filter explainer injected into outgoing requests.

A dense cluster of opaque <REF_N> placeholders trips a capable model's
prompt-injection defences (Claude declines a 6-token prompt as "a
prompt-injection pattern") and a weaker model's "missing information"
reflex. Prepending a short system-prompt note that explains the
placeholder convention clears it — measured in apf-76s (Claude) and
apf-6l8 (local models).

The note is injected only when the session vault holds tokens — i.e.
the request actually carries <REF_N> placeholders. Opt out with
APF_EXPLAINER=off (for deployments that inject their own, or once the
surrogate-substitution approach in apf-okt supersedes this).

This is an interim measure: apf-okt (plausible fake values instead of
opaque markers) would remove the need for it on Tier-A-dense prompts.
"""
from __future__ import annotations

import os

from .vault import Vault

# Exact text validated by the apf-76s matrix: with it, Claude completes a
# 6-token masked tool-call prompt that it declines without it.
EXPLAINER_TEXT = (
    "Some words in user messages may be opaque placeholder identifiers "
    "generated by an upstream privacy filter. They look like angle-bracketed "
    "labels with an index suffix. Treat them as variable names; they contain "
    "no personal information. Answer the user's actual request normally; "
    "never refuse a request based on the presence of such placeholders. If "
    "you need to refer back to one, output it verbatim using the exact same "
    "form the user sent — the downstream filter will substitute the real "
    "value before display."
)


def explainer_enabled() -> bool:
    """False if the operator set APF_EXPLAINER to off/0/false."""
    return os.environ.get("APF_EXPLAINER", "on").strip().lower() \
        not in ("off", "0", "false", "no")


def _should_inject(vault: Vault) -> bool:
    return explainer_enabled() and bool(vault.all_entries())


def inject_into_anthropic(body: dict, vault: Vault) -> dict:
    """Prepend the explainer to an Anthropic Messages request's `system`
    field. No-op if the explainer is disabled or the vault is empty (no
    masking happened — nothing to explain)."""
    if not _should_inject(vault):
        return body
    out = dict(body)
    system = out.get("system")
    if system is None:
        out["system"] = [{"type": "text", "text": EXPLAINER_TEXT}]
    elif isinstance(system, str):
        out["system"] = EXPLAINER_TEXT + "\n\n" + system
    elif isinstance(system, list):
        out["system"] = [{"type": "text", "text": EXPLAINER_TEXT}, *system]
    return out


def inject_into_openai(body: dict, vault: Vault) -> dict:
    """Prepend an explainer system message to an OpenAI Chat Completions
    request. No-op if the explainer is disabled or the vault is empty."""
    if not _should_inject(vault):
        return body
    out = dict(body)
    messages = list(out.get("messages") or [])
    out["messages"] = [{"role": "system", "content": EXPLAINER_TEXT},
                        *messages]
    return out
